#!/bin/bash
# ============================================================================
# Databricks App Setup Script
# Configures authentication and installs dependencies for local development
# ============================================================================

set -e

echo ""
echo "🚀 Databricks App Setup"
echo "========================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Track if uv is available
USE_UV=false

# ============================================================================
# Check Required Tools
# ============================================================================
check_requirements() {
    echo -e "${BLUE}Checking requirements...${NC}"
    echo ""
    
    # Check Databricks CLI
    if ! command -v databricks &> /dev/null; then
        echo -e "${RED}❌ Databricks CLI not found${NC}"
        echo ""
        echo "   Install the Databricks CLI:"
        echo "   https://docs.databricks.com/dev-tools/cli/install.html"
        echo ""
        echo "   Quick install (macOS/Linux):"
        echo "   curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh"
        echo ""
        exit 1
    fi
    echo -e "${GREEN}✓${NC} Databricks CLI: $(databricks --version 2>/dev/null | head -1)"
    
    # Check Python
    if ! command -v python3 &> /dev/null; then
        echo -e "${RED}❌ Python 3 not found${NC}"
        echo "   Install Python 3.10 or higher"
        exit 1
    fi
    echo -e "${GREEN}✓${NC} Python: $(python3 --version)"
    
    # Check jq (needed for deploy script)
    if ! command -v jq &> /dev/null; then
        echo -e "${YELLOW}⚠${NC} jq not found (optional, but recommended for deploy script)"
        echo "   Install: brew install jq (macOS) or apt install jq (Linux)"
    else
        echo -e "${GREEN}✓${NC} jq: $(jq --version)"
    fi
    
    # Check uv (Python package manager) - optional but recommended
    if command -v uv &> /dev/null; then
        echo -e "${GREEN}✓${NC} uv: $(uv --version) (recommended)"
        USE_UV=true
    else
        echo -e "${YELLOW}⚠${NC} uv not found - using pip instead"
        echo "   For faster installs, install uv: https://github.com/astral-sh/uv"
    fi
    
    # Check Node.js (for frontend)
    if command -v node &> /dev/null; then
        echo -e "${GREEN}✓${NC} Node.js: $(node --version)"
    else
        echo -e "${YELLOW}⚠${NC} Node.js not found - frontend development disabled"
    fi
    
    echo ""
}

# ============================================================================
# Configure Authentication
# ============================================================================
configure_auth() {
    echo -e "${BLUE}Configuring Databricks Authentication${NC}"
    echo ""
    echo "Choose authentication method:"
    echo ""
    echo "  1) Personal Access Token (PAT)"
    echo "     Best for: Quick setup, local development"
    echo "     Get token from: Workspace > User Settings > Access Tokens"
    echo ""
    echo "  2) Databricks CLI Profile"
    echo "     Best for: Production use, OAuth, multiple workspaces"
    echo "     Configure with: databricks auth login --host <url> --profile <name>"
    echo ""
    read -p "Enter choice (1 or 2): " auth_choice
    
    case $auth_choice in
        1)
            echo ""
            read -p "Databricks workspace URL (e.g., https://xxx.cloud.databricks.com): " db_host
            
            # Validate URL format
            if [[ ! "$db_host" =~ ^https:// ]]; then
                echo -e "${YELLOW}⚠ Adding https:// prefix${NC}"
                db_host="https://$db_host"
            fi
            
            read -sp "Personal Access Token: " db_token
            echo ""
            
            read -p "App name (default: my-databricks-app): " app_name
            app_name="${app_name:-my-databricks-app}"
            
            cat > .env.local << EOF
# Databricks Authentication (generated by setup.sh)
DATABRICKS_AUTH_TYPE=pat
DATABRICKS_HOST=${db_host}
DATABRICKS_TOKEN=${db_token}

# App Configuration
DATABRICKS_APP_NAME=${app_name}
EOF
            ;;
        2)
            echo ""
            echo "Available profiles:"
            databricks auth profiles 2>/dev/null || echo "  (no profiles configured)"
            echo ""
            read -p "Profile name: " profile_name
            
            read -p "App name (default: my-databricks-app): " app_name
            app_name="${app_name:-my-databricks-app}"
            
            cat > .env.local << EOF
# Databricks Authentication (generated by setup.sh)
DATABRICKS_AUTH_TYPE=databricks-cli
DATABRICKS_CONFIG_PROFILE=${profile_name}

# App Configuration
DATABRICKS_APP_NAME=${app_name}
EOF
            ;;
        *)
            echo -e "${RED}Invalid choice${NC}"
            exit 1
            ;;
    esac
    
    chmod 600 .env.local
    echo ""
    echo -e "${GREEN}✓ Authentication configured in .env.local${NC}"
    echo ""
}

# ============================================================================
# Validate Connection
# ============================================================================
validate_connection() {
    echo -e "${BLUE}Validating Databricks connection...${NC}"
    
    source .env.local
    
    if [ "$DATABRICKS_AUTH_TYPE" = "pat" ]; then
        export DATABRICKS_HOST
        export DATABRICKS_TOKEN
    else
        export DATABRICKS_CONFIG_PROFILE
    fi
    
    if databricks current-user me &> /dev/null; then
        echo ""
        echo -e "${GREEN}✓ Successfully connected to Databricks!${NC}"
        echo ""
        echo "  User: $(databricks current-user me --output json 2>/dev/null | jq -r '.userName // .displayName // "unknown"' 2>/dev/null || echo "connected")"
        echo "  Host: ${DATABRICKS_HOST:-$(databricks auth env 2>/dev/null | grep DATABRICKS_HOST | cut -d= -f2)}"
    else
        echo ""
        echo -e "${RED}❌ Failed to connect to Databricks${NC}"
        echo ""
        echo "Please check:"
        echo "  1. Your workspace URL is correct"
        echo "  2. Your token/profile is valid"
        echo "  3. You have network access to the workspace"
        echo ""
        echo "Delete .env.local and run setup again:"
        echo "  rm .env.local && ./scripts/setup.sh"
        exit 1
    fi
    echo ""
}

# ============================================================================
# Install Python Dependencies
# ============================================================================
install_python_deps() {
    echo -e "${BLUE}Installing Python dependencies...${NC}"
    
    if [ "$USE_UV" = true ]; then
        # Use uv for fast installation
        uv pip install -e ".[dev]" --quiet
    else
        # Fallback to pip
        pip install -e ".[dev]" --quiet
    fi
    
    echo -e "${GREEN}✓ Python dependencies installed${NC}"
    echo ""
}

# ============================================================================
# Install Node.js Dependencies (if frontend exists)
# ============================================================================
install_node_deps() {
    if [ -d "client" ] && [ -f "client/package.json" ]; then
        echo -e "${BLUE}Installing frontend dependencies...${NC}"
        
        cd client
        if command -v bun &> /dev/null; then
            bun install --silent
        elif command -v npm &> /dev/null; then
            npm install --silent
        else
            echo -e "${YELLOW}⚠ No npm or bun found - skipping frontend${NC}"
        fi
        cd ..
        
        echo -e "${GREEN}✓ Frontend dependencies installed${NC}"
        echo ""
    fi
}

# ============================================================================
# Generate requirements.txt
# ============================================================================
generate_requirements() {
    echo -e "${BLUE}Generating requirements.txt for deployment...${NC}"
    
    if [ -f "scripts/generate_requirements.py" ]; then
        python3 scripts/generate_requirements.py > /dev/null
        echo -e "${GREEN}✓ requirements.txt generated${NC}"
    fi
    echo ""
}

# ============================================================================
# Main Setup Flow
# ============================================================================
main() {
    check_requirements
    
    if [ ! -f ".env.local" ]; then
        configure_auth
    else
        echo -e "${YELLOW}⚠ .env.local already exists${NC}"
        echo "  Using existing configuration."
        echo "  To reconfigure, delete .env.local and run setup again."
        echo ""
    fi
    
    validate_connection
    install_python_deps
    install_node_deps
    generate_requirements
    
    echo "============================================"
    echo -e "${GREEN}🎉 Setup complete!${NC}"
    echo "============================================"
    echo ""
    echo "Next steps:"
    echo ""
    echo "  1. Start local development:"
    echo "     ${BLUE}./scripts/watch.sh${NC}"
    echo ""
    echo "  2. Open in browser:"
    echo "     http://localhost:8000       (API)"
    echo "     http://localhost:8000/docs  (API Documentation)"
    echo ""
    echo "  3. Deploy to Databricks:"
    echo "     ${BLUE}./scripts/deploy.sh --create${NC}"
    echo ""
}

main "$@"
